// Generated by CoffeeScript 1.4.0
(function() {
  var adjustment, initCascade, resizeListener, _ref;

  this.App = (_ref = window.App) != null ? _ref : {};

	/**
	 * 麻烦蕴豪看看这里的路径应该怎么设置
	 */
  App.BASEURL = 'http://localhost';

  App.TEST_IMAGES = ['/~Aquietzero/365wzs/img/ads/1.jpg', '/~Aquietzero/365wzs/img/ads/2.png', '/~Aquietzero/365wzs/img/ads/3.jpeg', '/~Aquietzero/365wzs/img/ads/4.jpg', '/~Aquietzero/365wzs/img/ads/5.png', '/~Aquietzero/365wzs/img/ads/6.png', '/~Aquietzero/365wzs/img/ads/7.jpg', '/~Aquietzero/365wzs/img/ads/8.png', '/~Aquietzero/365wzs/img/ads/9.jpg', '/~Aquietzero/365wzs/img/ads/10.jpg', '/~Aquietzero/365wzs/img/ads/11.jpg', '/~Aquietzero/365wzs/img/ads/13.png', '/~Aquietzero/365wzs/img/ads/14.png', '/~Aquietzero/365wzs/img/ads/15.jpg', '/~Aquietzero/365wzs/img/ads/16.jpg', '/~Aquietzero/365wzs/img/ads/17.png', '/~Aquietzero/365wzs/img/ads/18.jpg', '/~Aquietzero/365wzs/img/ads/20.jpg', '/~Aquietzero/365wzs/img/ads/21.jpg', '/~Aquietzero/365wzs/img/ads/23.jpg', '/~Aquietzero/365wzs/img/ads/24.png', '/~Aquietzero/365wzs/img/ads/25.png', '/~Aquietzero/365wzs/img/ads/26.png', '/~Aquietzero/365wzs/img/ads/27.jpg', '/~Aquietzero/365wzs/img/ads/28.jpg', '/~Aquietzero/365wzs/img/ads/29.jpg', '/~Aquietzero/365wzs/img/ads/30.jpg', '/~Aquietzero/365wzs/img/ads/31.jpg'];

  $(function() {
    var router;
    App.Helpers.showMessage(App.Views.Lightbox);
    adjustment();
    router = new App.Router;
    return Backbone.history.start({
      pushState: true
    });
  });

  initCascade = function() {
    var $container;
    $container = $('#cascade-container');
    return $container.imagesLoaded(function() {
      return $container.masonry({
        itemSelector: '.image-block'
      });
    });
  };

  adjustment = function() {
    var $first_block, content_width, margin, num, padding, unit_width;
    $first_block = $($('.image-block')[0]);
    content_width = $('#cascade-container').width();
    unit_width = $first_block.width();
    margin = 10;
    num = Math.floor(content_width / (unit_width + 2 * margin));
    padding = (content_width - num * (unit_width + 2 * margin)) / 2;
    return $('#cascade-container').css('paddingLeft', padding - 5);
  };

  resizeListener = function() {
    var listenResizeEvent;
    listenResizeEvent = function() {
      var delta, resizeend, rtime, timeout;
      rtime = new Date(1, 1, 2000, 12, 0, 0);
      timeout = false;
      delta = 200;
      $(window).resize(function() {
        rtime = new Date();
        if (timeout === false) {
          timeout = true;
          return setTimeout(resizeend, delta);
        }
      });
      return resizeend = function() {
        if (new Date() - rtime < delta) {
          return setTimeout(resizeend, delta);
        } else {
          timeout = false;
          return adjustment();
        }
      };
    };
    return listenResizeEvent();
  };

}).call(this);
