// Generated by CoffeeScript 1.4.0
(function() {
  var adjustment, _ref;

  this.App = (_ref = this.App) != null ? _ref : {};

  App.BASEURL = '/~Aquietzero/365wzs';

  $(function() {
    var $container, listenResizeEvent;
    Zhelper.showMessage(App.Lightbox);
    $container = $('#cascade-container');
    $container.imagesLoaded(function() {
      return $container.masonry({
        itemSelector: '.image-block'
      });
    });
    $('body').append(App.Lightbox.$el);
    adjustment();
    listenResizeEvent = function() {
      var delta, resizeend, rtime, timeout;
      rtime = new Date(1, 1, 2000, 12, 0, 0);
      timeout = false;
      delta = 200;
      $(window).resize(function() {
        rtime = new Date();
        if (timeout === false) {
          timeout = true;
          return setTimeout(resizeend, delta);
        }
      });
      return resizeend = function() {
        if (new Date() - rtime < delta) {
          return setTimeout(resizeend, delta);
        } else {
          timeout = false;
          return adjustment();
        }
      };
    };
    listenResizeEvent();
    $('.favor').click(function() {
      console.log('click!');
      Zhelper.createLikeForm(App.Lightbox, App);
      return App.Lightbox.show();
    });
    return $('.at').click(function() {
      Zhelper.createAtForm(App.Lightbox, App);
      return App.Lightbox.show();
    });
  });

  adjustment = function() {
    var $first_block, content_width, margin, num, padding, unit_width;
    $first_block = $($('.image-block')[0]);
    content_width = $('#cascade-container').width();
    unit_width = $first_block.width();
    margin = 10;
    num = Math.floor(content_width / (unit_width + 2 * margin));
    padding = (content_width - num * (unit_width + 2 * margin)) / 2;
    return $('#cascade-container').css('paddingLeft', padding - 5);
  };

}).call(this);
