// Generated by CoffeeScript 1.4.0
(function() {
  var App, _ref;

  App = (_ref = window.App) != null ? _ref : {};

  App.Helpers = {
    create: function(dom, attrs, content) {
      var $dom, key, val;
      content = content != null ? content : '';
      $dom = $("<" + dom + "></" + dom + ">");
      for (key in attrs) {
        val = attrs[key];
        $dom.attr(key, val);
      }
      if (dom === 'img') {
        return $dom;
      } else {
        $dom.html(content);
        return $dom;
      }
    },
    plural: function(noun, num) {
      if (num === 0) {
        return "No " + noun;
      } else if (num === 1) {
        return "1 " + noun;
      } else {
        return "" + num + " " + noun;
      }
    },
    createLoginForm: function(parent) {
      var $login_form, login_form_template;
      login_form_template = $('#login-template').html();
      $login_form = $(login_form_template);
      parent.setWidget($login_form);
      return $login_form.trigger('spinner.stop');
    },
    showMessage: function(parent) {
      var $message, $messagebox;
      $message = $('#message');
      if ($message.html() !== '') {
        $messagebox = this.create('div');
        $messagebox.width(300).height(150).addClass('messagebox').html($message.html());
        parent.show();
        return parent.setWidget($messagebox);
      }
    },
    delay: function(msec, func) {
      return setTimeout(func, msec);
    }
  };

}).call(this);
