// Generated by CoffeeScript 1.4.0
(function() {
  var _ref;

  this.App = (_ref = this.App) != null ? _ref : {};

  this.App.Lightbox = (function() {
    var Lightbox;
    Lightbox = (function() {

      function Lightbox() {
        this.$wrapper = Zhelper.create('div', {
          id: 'lightbox-wrapper'
        });
        this.$content = Zhelper.create('div', {
          id: 'lightbox'
        });
        this.$wrapper.append(this.$content);
        this.$el = this.$wrapper;
        this.init();
      }

      Lightbox.prototype.init = function() {
        var _this = this;
        this.$wrapper.click(function(e) {
          return _this.hide();
        });
        this.$content.click(function(e) {
          return e.stopPropagation();
        });
        return this.$content.on({
          'spinner.stop': function(e) {
            return App.ZSpinner.stop();
          }
        });
      };

      Lightbox.prototype.show = function() {
        this.$content.empty();
        App.ZSpinner.spin();
        $('body').addClass('ban-scroll');
        return this.$wrapper.fadeIn();
      };

      Lightbox.prototype.hide = function() {
        this.$wrapper.fadeOut();
        return $('body').removeClass('ban-scroll');
      };

      Lightbox.prototype.trigger = function(event, data) {
        return this.$content.trigger(event, data);
      };

      Lightbox.prototype.setWidget = function($widget) {
        var height, width;
        width = $(window).width();
        height = $(window).height();
        this.$content.append($widget);
        return this.$content.css({
          width: $widget.width(),
          height: $widget.height(),
          marginTop: (height - $widget.height()) / 2
        });
      };

      return Lightbox;

    })();
    return new Lightbox;
  })();

}).call(this);
