// Generated by CoffeeScript 1.4.0
(function() {
  var App, Router, _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  App = (_ref = window.App) != null ? _ref : {};

  Router = (function(_super) {

    __extends(Router, _super);

    function Router() {
      return Router.__super__.constructor.apply(this, arguments);
    }

    Router.prototype.routes = {
      "365wzs/": 'index',
      "365wzs/main": 'index',
      "365wzs/shares": 'index',
      "*actions": 'default'
    };

    Router.prototype["default"] = function(actions) {};

    Router.prototype.index = function() {
      var col, cols_num, i, post, posts, postsCollection, row, size, src, zexpo, _i, _len, _ref1;
      $.ajax({
        url: '/365wzs/pipe/10/0',
        success: function(data) {
          return console.log(data);
        }
      });
      posts = [];
      cols_num = 8;
      size = 1000 / cols_num;
      _ref1 = App.TEST_IMAGES;
      for (i = _i = 0, _len = _ref1.length; _i < _len; i = ++_i) {
        src = _ref1[i];
        row = Math.floor(i / cols_num);
        col = i % cols_num;
        post = {
          top: row * size,
          left: col * size,
          src: src
        };
        posts.push(post);
      }
      postsCollection = new App.Collections.Posts(posts);
      zexpo = new App.Views.ZExpo({
        collection: postsCollection
      });
      return $(document.body).append(zexpo.render().el);
    };

    return Router;

  })(Backbone.Router);

  App.Router = Router;

}).call(this);
