// Generated by CoffeeScript 1.4.0
(function() {
  var _ref;

  this.App = (_ref = this.App) != null ? _ref : {};

  this.App.ZSpinner = (function() {
    var Spinner;
    Spinner = (function() {

      function Spinner() {
        this.$el = Zhelper.create('div', {
          'id': 'indicator'
        });
        this.$el.css({
          position: 'fixed',
          top: $(window).height() / 2,
          left: $(window).width() / 2
        });
        this.settings = {
          lines: 12,
          length: 7,
          width: 5,
          radius: 10,
          color: '#000',
          speed: 1,
          trail: 100,
          shadow: true
        };
      }

      Spinner.prototype.spin = function() {
        return this.$el.spin(this.settings);
      };

      Spinner.prototype.stop = function() {
        return this.$el.spin(false);
      };

      return Spinner;

    })();
    return new Spinner;
  })();

  console.log(App, 'spinner');

}).call(this);
