// Generated by CoffeeScript 1.4.0
(function() {
  var App, Post, _ref, _ref1,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  App = (_ref = window.App) != null ? _ref : {};

  App.Models = (_ref1 = App.Models) != null ? _ref1 : {};

  console.log(App);

  Post = (function(_super) {

    __extends(Post, _super);

    function Post() {
      return Post.__super__.constructor.apply(this, arguments);
    }

    Post.prototype.defaults = {
      top: 0,
      left: 0,
      src: '/test/post'
    };

    return Post;

  })(Backbone.Model);

  App.Models.Post = Post;

}).call(this);
