// Generated by CoffeeScript 1.4.0
(function() {
  var App, SimpleUser, _ref, _ref1,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  App = (_ref = window.App) != null ? _ref : {};

  App.Models = (_ref1 = App.Models) != null ? _ref1 : {};

  SimpleUser = (function(_super) {

    __extends(SimpleUser, _super);

    function SimpleUser() {
      return SimpleUser.__super__.constructor.apply(this, arguments);
    }

    SimpleUser.prototype.defaults = {
      username: 'Aquietzero',
      pic_url: 'default-avatar.png'
    };

    return SimpleUser;

  })(Backbone.Model);

  App.Models.SimpleUser = SimpleUser;

}).call(this);
