// Generated by CoffeeScript 1.4.0
(function() {
  var App, Posts, _ref, _ref1,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  App = (_ref = window.App) != null ? _ref : {};

  App.Collections = (_ref1 = App.Collections) != null ? _ref1 : {};

  Posts = (function(_super) {

    __extends(Posts, _super);

    function Posts() {
      return Posts.__super__.constructor.apply(this, arguments);
    }

    Posts.prototype.model = App.Models.Post;

    return Posts;

  })(Backbone.Collection);

  App.Collections.Posts = Posts;

}).call(this);
