// Generated by CoffeeScript 1.4.0
(function() {
  var App, DetailPosts, _ref, _ref1,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  App = (_ref = window.App) != null ? _ref : {};

  App.Views = (_ref1 = App.Views) != null ? _ref1 : {};

  DetailPosts = (function(_super) {

    __extends(DetailPosts, _super);

    function DetailPosts() {
      return DetailPosts.__super__.constructor.apply(this, arguments);
    }

    DetailPosts.prototype.el = '#tab-content';

    DetailPosts.prototype.render = function() {
      var _this = this;
      this.$el.empty();
      this.collection.each(function(detail_post) {
        var detail_post_view;
        detail_post_view = new App.Views.DetailPost({
          model: detail_post
        });
        return _this.$el.append(detail_post_view.render().el);
      });
      return this;
    };

    return DetailPosts;

  })(Backbone.View);

  App.Views.DetailPosts = DetailPosts;

}).call(this);
