// Generated by CoffeeScript 1.4.0
(function() {
  var App, SimpleUser, _ref, _ref1,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  App = (_ref = window.App) != null ? _ref : {};

  App.Views = (_ref1 = App.Views) != null ? _ref1 : {};

  SimpleUser = (function(_super) {

    __extends(SimpleUser, _super);

    function SimpleUser() {
      return SimpleUser.__super__.constructor.apply(this, arguments);
    }

    SimpleUser.prototype.tagName = 'div';

    SimpleUser.prototype.className = 'user';

    SimpleUser.prototype.template = $('#simple-user-template').html();

    SimpleUser.prototype.render = function() {
      this.$el.html(_.template(this.template, this.model.toJSON()));
      return this;
    };

    return SimpleUser;

  })(Backbone.View);

  App.Views.SimpleUser = SimpleUser;

}).call(this);
