// Generated by CoffeeScript 1.4.0
(function() {
  var App, UserBasicInfo, _ref, _ref1,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  App = (_ref = window.App) != null ? _ref : {};

  App.Views = (_ref1 = App.Views) != null ? _ref1 : {};

  UserBasicInfo = (function(_super) {

    __extends(UserBasicInfo, _super);

    function UserBasicInfo() {
      return UserBasicInfo.__super__.constructor.apply(this, arguments);
    }

    UserBasicInfo.prototype.el = '#user-basic-info';

    UserBasicInfo.prototype.events = {
      'click .follows': 'showFollows',
      'click .fans': 'showFans'
    };

    UserBasicInfo.prototype.showFollows = function() {
      var follows;
      follows = new App.Collections.SimpleUsers;
      follows.url = "" + App.BASEURL + "/hail/follows/" + this.options.user_id;
      return follows.fetch({
        success: function() {
          var followsView;
          followsView = new App.Views.SimpleUsers({
            collection: follows
          });
          return followsView.render();
        },
        error: function(obj, res) {
          return console.log(res);
        }
      });
    };

    UserBasicInfo.prototype.showFans = function() {
      var fans;
      fans = new App.Collections.SimpleUsers;
      fans.url = "" + App.BASEURL + "/hail/fans/" + this.options.user_id;
      return fans.fetch({
        success: function() {
          var fansView;
          console.log(fans);
          fansView = new App.Views.SimpleUsers({
            collection: fans
          });
          return fansView.render();
        },
        error: function(obj, res) {
          return console.log(res);
        }
      });
    };

    return UserBasicInfo;

  })(Backbone.View);

  App.Views.UserBasicInfo = UserBasicInfo;

}).call(this);
