// Generated by CoffeeScript 1.4.0
(function() {
  var App, ZExpo, _ref, _ref1,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  App = (_ref = window.App) != null ? _ref : {};

  App.Views = (_ref1 = App.Views) != null ? _ref1 : {};

  ZExpo = (function(_super) {

    __extends(ZExpo, _super);

    function ZExpo() {
      return ZExpo.__super__.constructor.apply(this, arguments);
    }

    ZExpo.prototype.el = '#zexpo';

    ZExpo.prototype.initialize = function() {};

    ZExpo.prototype.addOne = function(post) {
      var postView;
      postView = new App.Views.Post({
        model: post
      });
      return this.$el.append(postView.render().el);
    };

    ZExpo.prototype.render = function() {
      this.collection.each(this.addOne, this);
      return this;
    };

    return ZExpo;

  })(Backbone.View);

  App.Views.ZExpo = ZExpo;

}).call(this);
